# Generated by Django 4.2.7 on 2023-12-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rno', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=255)),
                ('std', models.CharField(max_length=10)),
                ('encoding', models.TextField()),
            ],
        ),
    ]
